name: Deployment pipeline

on:
  push:
    paths:
      - Docker*
      - inferring*
      - models/supervised/*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nltk gensim matplotlib pandas seaborn python-dotenv wordcloud StackAPI scikit-learn pytest 

    - name: Running the tests
      run: pytest test_text_processing.py

    - name: Generate deployment package
      run: zip -r release.zip Dockerfile Dockerrun.aws.json inferring_application.py inferring_application_requirements.txt models/supervised/*
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: inferring-service
        environment_name: inferring-service-env
        version_label: ${{ github.run_number }}
        region: eu-west-3
        deployment_package: release.zip


